# Collecte de données

## Enjeux

- Enjeux méthodologiques très liés au changement de paradigme de collecte

- Plus un _design ad hoc_ 


## Webscraping (1/3)

- [**Webscraping**]{.orange} : extraction du contenu de sites Internet
- Information textuelle [**très riche**]{.orange} sur Internet, mobilisable à des fins de statistique publique
- [**Enjeux**]{.orange} :
    - [**Techniques**]{.blue2} : évolution des pages web, interactivité des sites
    - [**Légaux**]{.blue2} : jurisprudences, directives de 2020 de la CNIL
- [**Bonnes pratiques**]{.orange} : `robots.txt`

## Webscraping (2/3)

- [**En pratique**]{.orange} :
    - `Python` : `BeautifulSoup` (parser), `Scrapy` (crawler)
    - `R` : `httr`, `rvest`, `polite`
    - `Selenium` : outils d'automatisation
- [**Excellente formation** d'Antoine Palazzolo](https://inseefrlab.github.io/formation-webscraping/)

## Webscraping (3/3)

- Prix dans le [**domaine de l'hôtellerie**]{.orange} : scraping du site [Booking.com](https://www.booking.com/)
- Vente d'[**articles électroniques**]{.orange} :
    - [Boulanger](https://www.boulanger.com/)
    - [Rue du commerce](https://www.rueducommerce.fr/)
- Scraping du [**site de la SNCF**]{.orange} : collecte quotidienne pour capter la volatilité des prix
- Scrapping des offres d'emploi (projet [**Jocas**](https://dares.travail-emploi.gouv.fr/enquete-source/jocas)) par la Dares

## Utilisation d'API

- [**API**]{.orange} : interface de programmation
- Mode [**préférentiel**]{.orange} de collecte de données :
    - Plus de garanties sur [**la qualité**]{.blue2}
    - [**Reproductibilité**]{.blue2}
    - ...
- Avec `Python` : `requests`
